In [14]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [15]:
tensor_one = tf.constant(4)
tensor_one
tensor_two = tf.constant([2,2,34,4])
tensor_two

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  2, 34,  4], dtype=int32)>

In [40]:
tensor_three = tf.Variable([[2,2,2],
                            [2,2,2],
                            [2,2,4]])
# tensor_three.ndim
tensor_four = tf.constant(tensor_three)
tensor_four.ndim

2

In [47]:
random_one = tf.random.Generator.from_seed(32)
random_one = random_one.uniform(shape = [3,2,2])
random_one
#Greate things go incredably
random_two = tf.random.Generator.from_seed(21).uniform(shape = [4,4],minval = 20, maxval =30)
shuffle_random_two = tf.random.shuffle(random_two)
random_two, shuffle_random_two, random_two == shuffle_random_two


(<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[24.1687  , 27.472572, 28.982729, 29.517384],
        [20.966888, 29.433586, 26.924688, 29.86995 ],
        [29.92509 , 22.040176, 22.639889, 27.94028 ],
        [27.197464, 24.784569, 22.136604, 27.84128 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[20.966888, 29.433586, 26.924688, 29.86995 ],
        [29.92509 , 22.040176, 22.639889, 27.94028 ],
        [24.1687  , 27.472572, 28.982729, 29.517384],
        [27.197464, 24.784569, 22.136604, 27.84128 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=bool, numpy=
 array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True]])>)