# we are going to cover introduction to tensorFlow
More specifically, we're going to conver:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tesnors & NumPy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself.

In [1]:

import tensorflow as tf
print(tf.__version__)

2.19.0


In [2]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimension s of tensor (ndim stands for number of dimensions)
scalar.ndim


0

In [4]:
# create a vector
vector = tf.constant([21,24])
vector.ndim

1

In [5]:
# create matrix (has more than 1 dimension )
matrix = tf.constant([[21,24],[234,24]])
matrix
matrix.ndim

2

In [6]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [21.,24.],
                              [21., 24.]],dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [21., 24.],
       [21., 24.]], dtype=float16)>

In [7]:
another_matrix.ndim

2

In [8]:
# Let's create tensor
tensor = tf.constant([[[1,2,3],
                    [12,24,43]],
                     [[234,43,5],
                      [24,242,24]],
                     [[2423,224,24],
                      [242,242,24]] ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[   1,    2,    3],
        [  12,   24,   43]],

       [[ 234,   43,    5],
        [  24,  242,   24]],

       [[2423,  224,   24],
        [ 242,  242,   24]]], dtype=int32)>

In [9]:
tensor.ndim

3

In [10]:
 # create the same tnsor with tf.Variable as above
changeable_tensor = tf.Variable([21,24])
unchangeable_tensor = tf.constant([21,24])
changeable_tensor, unchangeable_tensor



(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([21, 24], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([21, 24], dtype=int32)>)

In [11]:
# let's try change one of the elements in our changeable tensor using .assign()
changeable_tensor.assign([22,22])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([22, 22], dtype=int32)>

In [12]:
# Let's try change our unchangable tensor
unchangeable_tensor
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([21, 24], dtype=int32)>

# creating random tensors


In [64]:
  # Let's create  two random tensor
random_one = tf.random.Generator.from_seed(42)
random_one = random_one.normal(shape = [3,4,2])
random_two = tf.random.Generator.from_seed(42)
random_two = random_two.normal(shape= [3,4,2])
random_one, random_two, random_one == random_two
random_three = tf.random.Generator.from_seed(42)
random_three = random_three.normal(shape=[3,4,2])
random_one, random_two, random_three, random_three == random_one

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702],
         [ 0.07595026, -1.2573844 ],
         [-0.23193765, -1.8107855 ],
         [ 0.09988727, -0.50998646]],
 
        [[-0.7535806 , -0.5716629 ],
         [ 0.1480774 , -0.23362991],
         [-0.3522796 ,  0.40621266],
         [-1.0523509 ,  1.2054597 ]],
 
        [[ 1.6874489 , -0.44629744],
         [-2.3410842 ,  0.99009085],
         [-0.08763231, -0.635568  ],
         [-0.6161736 , -1.9441465 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702],
         [ 0.07595026, -1.2573844 ],
         [-0.23193765, -1.8107855 ],
         [ 0.09988727, -0.50998646]],
 
        [[-0.7535806 , -0.5716629 ],
         [ 0.1480774 , -0.23362991],
         [-0.3522796 ,  0.40621266],
         [-1.0523509 ,  1.2054597 ]],
 
        [[ 1.6874489 , -0.44629744],
         [-2.3410842 ,  0.99009085],
         [-0.08763231, -0.635568  ],
         [-0.6

In [65]:
not_shuffled = tf.random.Generator.from_seed(1)
not_shuffled = not_shuffled.uniform(shape = [2,2], minval = 10, maxval = 20)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[12.926306, 19.921692],
       [17.87495 , 13.906511]], dtype=float32)>

In [15]:
# other ways to make tensor
tf.ones(shape = (3,3))
zeros_tensor = tf.zeros(shape = [ 3,2])
zeros_tensor
# you can convert numPy array into tenors, the main diffference between tensor and numPy is that tensor is much faster run on a GPU computing


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [67]:
import numpy as np
numpy_A = np.arange( 1,49,2, dtype = np.float16)
numpy_A
A = tf.constant(  numpy_A, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[ 1.,  3.,  5.,  7.],
        [ 9., 11., 13., 15.],
        [17., 19., 21., 23.]],

       [[25., 27., 29., 31.],
        [33., 35., 37., 39.],
        [41., 43., 45., 47.]]], dtype=float16)>

### Getting information from tensors
 when dealing with tensors you probably want to aware the following attriblue
 * shape
 * rank
 * axis or dimension
 * size

In [17]:
# create rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [68]:
rank_4_tensor.shape,rank_4_tensor.ndim, tf.size(rank_4_tensor)
# get various attribute of our tensor


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [69]:
rank_4_tensor[:,:1,:2,:2]

<tf.Tensor: shape=(2, 1, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [70]:
 # create a rank two tensor
rank_two_tensor = rank_4_tensor[:,:,:,]
rank_two_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
tensor_two = tf.constant([[23,23],
                          [2,2]])
tensor_two
tensor_three =tensor_two[..., tf.newaxis]
tensor_three, tensor_three.ndim

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[23],
         [23]],
 
        [[ 2],
         [ 2]]], dtype=int32)>,
 3)

In [74]:
tf.expand_dims(tensor_two, axis = -1),tensor_two, tensor_two.ndim

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[23],
         [23]],
 
        [[ 2],
         [ 2]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[23, 23],
        [ 2,  2]], dtype=int32)>,
 2)

In [73]:
tensor_four = tf.constant([[2,3],
                           [32,23]])
tf.expand_dims(tensor_four,axis = 1 )
tensor_four, tensor_four.ndim


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 2,  3],
        [32, 23]], dtype=int32)>,
 2)

## manipulation of tensor( tensor operations)


In [83]:
tensor = tf.constant([[21,24],[21,24]])
tensor = tensor * 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210, 240],
       [210, 240]], dtype=int32)>

In [84]:
tensor_test = tf.constant([2,2])
tensor_test.ndim

1

In [85]:
tensor_test * 12
tensor_test

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

**matrix multiplication in tensor**
In machine learning matrix multiplication is one of the most tensor operation


In [86]:
# matrix multiplication in tensorflow
print(tensor_test)
tf.multiply(tensor_test,tensor_test)
tensor_a = tf.constant([[21,24],[22,4]])
tensor_b = tf.constant([[2,24],[10,20]])
random_tensor_a = tf.random.Generator.from_seed(21)
random_tensor_b = tf.random.Generator.from_seed(21)
random_tensor_a = random_tensor_a.uniform(shape = [3,2], dtype = tf.float32)
random_tensor_b = random_tensor_b.normal([3,2], dtype = tf.float32)
tf.matmul(random_tensor_a, random_tensor_b, transpose_b= True)



tf.Tensor([2 2], shape=(2,), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5684129 ,  0.27268285,  1.2000879 ],
       [-1.2098088 ,  0.29649153,  1.251827  ],
       [-0.14939064,  0.40366158,  1.8385632 ]], dtype=float32)>

 **The dot product**
 Matrix multiplication s also refered to as the dot product you can perform matrix mulitplication using:
 * `tf.matmul()`
 * `tf.tensordot()`


In [88]:
# perform the dot product on X and Y (requires X or Y to be transpose)
# import numpy as np
X = np.arange(1,7, dtype=np.int32)
Y = np.arange(7,13, dtype=np.int32)
X = tf.constant(X, shape=(3,2))
Y = tf.constant(Y, shape = (3,2))
tf.tensordot(tf.transpose(X),Y, [[0],[1]]), tf.matmul(X,Y,True)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

In [29]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [30]:
# Perfomr matrix multiplication between X and Y ( Reshaped)
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [31]:
# check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")

print("Y reshpaed to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")
print("Transposed Y: ")
print(tf.transpose(Y))


Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshpaed to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### change the data type of a tensor

In [89]:
# create a new tensor with a default datatye float32
B = tf.constant([1.7,7.4])
B.dtype
C = tf.constant([21,24])
C.dtype

tf.int32

In [33]:
# change from flaot 32 to float16
B = tf.cast(B, dtype= tf.float16)
B.dtype
# change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E.dtype
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16.dtype, E.dtype

(tf.float16, tf.float32)

### aggregation
aggretating tensors = condensing them from multiple values down to a smaller amount of values.

In [34]:
# Get the absolute values
D = tf.constant([-2,-23])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -2, -23], dtype=int32)>

In [35]:
tf.abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 23], dtype=int32)>

### Let's go through the following forms of aggregation
* Ge the minimum
* get the maximun
* get the mean fo a tensor
* get the sum of a tensor

In [36]:
aggregated_tensor = tf.constant(np.random.randint(-10, 50, size = 27),shape = (3,3,3))
max_value = tf.reduce_max(aggregated_tensor)
min_value = tf.math.reduce_min(aggregated_tensor)
sum_value = tf.math.reduce_sum(aggregated_tensor)
average_value = tf.math.reduce_mean(aggregated_tensor)

print(f"Data of the aggregated_tensor aggregation value.{aggregated_tensor.numpy}\nnumber of elements: {tf.size(aggregated_tensor)}")
print("max value: ",max_value.numpy())
print("min value: ", min_value.numpy())
print("average value: ", average_value.numpy())
print("Total sum: ", sum_value.numpy())

Data of the aggregated_tensor aggregation value.<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[42, -3, 16],
        [-6, 18, 34],
        [-7, 14, 27]],

       [[13, 17, 49],
        [42, -8, 42],
        [32, 45, -2]],

       [[-6, 45, 16],
        [15, 32, 29],
        [12, 44, 26]]])>>
number of elements: 27
max value:  49
min value:  -8
average value:  21
Total sum:  578


⛑ **Exercise:** Find variance and standard divation of aggregated_tensor

In [37]:
variance = tf.math.reduce_variance(tf.cast(aggregated_tensor,dtype=tf.float32))
standard_divation = tf.math.reduce_std(tf.cast(aggregated_tensor,dtype=tf.float32))
variance.numpy(), standard_divation.numpy()

(np.float32(326.38962), np.float32(18.066256))

 ### find the positional maximum and minimum

In [38]:
# create a new tensor for finding positional mininum and maximum
tf.random.set_seed(21)
F = tf.random.uniform(shape = [50], seed = 21)
#Find the positional maximum
max_value_index = tf.argmax(F)
max_value_index
#Index on our largest value position
F[tf.argmax(F)]
# check for equality
F[max_value_index] == tf.math.reduce_max(F)
# Find the positional minimum
min_value_index = tf.argmin(F)
# check the equality
tf.math.reduce_min(F) == F[min_value_index]




<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor( removing all single dimensions)

In [39]:
tf.random.set_seed(21)
G = tf.constant(tf.random.uniform( shape = [50]),shape = [1,1,1,1,50])
G
# squeez G
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.02487183, 0.86122084, 0.2314794 , 0.4261533 , 0.07033372,
       0.58401775, 0.7013489 , 0.754992  , 0.3136698 , 0.08784151,
       0.5750065 , 0.41419947, 0.8238722 , 0.95380235, 0.66692805,
       0.84758234, 0.9837047 , 0.518342  , 0.58628106, 0.63801444,
       0.32165027, 0.50736034, 0.2782383 , 0.6642864 , 0.9852179 ,
       0.23556495, 0.605816  , 0.27656388, 0.00503111, 0.59167767,
       0.27659   , 0.1920625 , 0.74792933, 0.4232911 , 0.35802603,
       0.09356582, 0.80920005, 0.9766257 , 0.8915812 , 0.18043363,
       0.53957355, 0.4725902 , 0.17278957, 0.74056053, 0.7265396 ,
       0.8814677 , 0.20510364, 0.9970554 , 0.5058135 , 0.10387874],
      dtype=float32)>

### One-hot encoding tensors

In [40]:
one_hot_tensor = tf.one_hot(np.arange(1,20,2), depth=4  , on_value="ON", off_value="OFF")
one_hot_tensor

<tf.Tensor: shape=(10, 4), dtype=string, numpy=
array([[b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON'],
       [b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF']], dtype=object)>

### Squaring, log, square root

In [90]:
# Create a new tensor
H = tf.range(1,10)
H
# Square root
tf.square(H),tf.sqrt(tf.cast(H, dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>)

In [42]:
# Find log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor vs numPy
Tensorflow interacts beautifully with NumPy arrays

In [43]:
J =tf.constant(np.array([3.,4.,7.,10.]))
J
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))
# convernt tensor J to a NumPy array
J.numpy() == np.array(J), type(J)

(array([ True,  True,  True,  True]),
 tensorflow.python.framework.ops.EagerTensor)

In [91]:
# We have test performance of TPU, CPU and GPU accelarator of tensors
import tensorflow as tf

import time
start_time = time.time()
tensor = tf.random.uniform(shape = [23,23], minval = 2999, maxval=202022 )
tensor = tensor * 212
end_time = time.time()
print(f"used time:{end_time - start_time}")


used time:0.00501561164855957


In [92]:
# check runtime devices ,cpu,tpu or gpu
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [46]:
# !echo "# tensorflow_fundamental_exercises" >> README.md
# !git init
# !git add README.md
# !git commit -m "first commit"
!git config --global user.email "you@example.com"
!git config --global user.name "Your Name"
!git branch -M main
!git remote add origin git@github.com:mogesTesema/tensorflow_fundamental_exercises.git
!git push -u origin main

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git


In [47]:
!git remote add origin git@github.com:mogesTesema/tensorflow_fundamental_exercises.git
!git branch -M main
!git push -u origin main

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git


In [48]:
!git init


hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [49]:
#!git status
! git config --global user.name "mogesTesema"
! git config --global user.email "mogesastu2124@gmail.com"


In [50]:
!git branch -M main

In [51]:
!git status

On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	sample_data/

nothing added to commit but untracked files present (use "git add" to track)


In [52]:
!git remote add origin git@github.commit:mogesTesema/tensorflow_fundamental_exercises.git

In [53]:
!git add .

In [54]:
!git status

On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .config/.last_opt_in_prompt.yaml
	new file:   .config/.last_survey_prompt.yaml
	new file:   .config/.last_update_check.json
	new file:   .config/active_config
	new file:   .config/config_sentinel
	new file:   .config/configurations/config_default
	new file:   .config/default_configs.db
	new file:   .config/gce
	new file:   .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
	new file:   .config/logs/2025.09.05/13.34.55.296120.log
	new file:   .config/logs/2025.09.05/13.35.23.887773.log
	new file:   .config/logs/2025.09.05/13.35.32.844388.log
	new file:   .config/logs/2025.09.05/13.35.39.627717.log
	new file:   .config/logs/2025.09.05/13.35.48.538414.log
	new file:   .config/logs/2025.09.05/13.35.49.276498.log
	new file:   sample_data/README.md
	new file:   sample_data/anscombe.json
	new file:   sample_data/california_housing_test.csv
	new file:   sampl

In [55]:
!git reset

In [56]:
!git status

On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	sample_data/

nothing added to commit but untracked files present (use "git add" to track)


In [57]:
!ls

sample_data


In [58]:
! cd sample_data/

In [59]:
!ls

sample_data


In [60]:
!cd tensorflow_fundamental/

/bin/bash: line 1: cd: tensorflow_fundamental/: No such file or directory


In [61]:
!ls

sample_data
